/* Generate brand.html — the same app in KinaPT's colours.

   A comparison build, not a fork. It is produced from index.html by swapping
   the palette, so the two never drift: rerun this after any change to
   index.html and the branded copy picks it up.

       node tools/build-brand.js

   Why it stays dark: the whole interface is additive light on black — the
   bloom pass composites with 'lighter', so every glow depends on a dark ground.
   Dropping the app onto the KinaPT cream would not be a recolour, it would be
   a different renderer. This takes the brand's hues and runs them on the HUD's
   own ground: sage where the cyan was, bronze where the gold was, and the deep
   teal from the app's exercise circles as the background.
*/
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');

/* Sampled from the KinaPT app screenshot — sage card #9BC3B3, deep teal circle
   interiors #12504C, bronze headings #7C6239 — then adjusted for a dark ground.

   The sage itself does not survive here: it is pale and low-chroma, so the
   additive bloom washes it straight to white and the whole interface reads
   grey. What carries the brand across is the HUE, not the exact swatch, so the
   line colour is the same green-teal family at the saturation this rendering
   needs, and the pale sage is kept for highlights only, where blowing out to
   near-white is the intended effect. The bronze is lifted from ink-brown to a
   light gold for the same reason. */
const BRAND = {
  css: {
    '--cyan': '#4FC7A4',
    '--cyan-hot': '#C7F2E1',
    '--cyan-dim': 'rgba(79, 199, 164, 0.42)',
    '--cyan-faint': 'rgba(79, 199, 164, 0.10)',
    '--orange': '#D9A85C',
    '--red': '#DE7361',
    '--green': '#7FCBA1',
    '--bg': '#04120F',
    '--panel': 'rgba(11, 40, 37, 0.86)',
    '--text': '#DCEAE3'
  },
  // Canvas colours, as "r,g,b" so they can be dropped into rgba() strings.
  canvas: {
    blue: '79,199,164',
    hot: '199,242,225',
    gold: '217,168,92',
    magenta: '217,143,168'
  }
};

const src = fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8');

// --- palette block
const rootRe = /:root \{[\s\S]*?\n  \}/;
if (!rootRe.test(src)) {
  console.error('Could not find the :root block in index.html — has it moved?');
  process.exit(1);
}
const rootBlock = ':root {\n' +
  '    /* KinaPT brand palette — generated by tools/build-brand.js.\n' +
  '       Edit the source there, not here; this file is overwritten. */\n' +
  Object.entries(BRAND.css).map(([k, v]) => `    ${k}: ${v};`).join('\n') +
  '\n  }';

let out = src.replace(rootRe, rootBlock);

// --- canvas palette, set before the module loads so it is read at definition
const moduleTag = '<script type="module" src="./app.js"></script>';
if (!out.includes(moduleTag)) {
  console.error('Could not find the app.js module tag in index.html — has it moved?');
  process.exit(1);
}
out = out.replace(moduleTag,
  '<script>window.KINA_PALETTE = ' + JSON.stringify(BRAND.canvas) + ';</script>\n' +
  moduleTag);

// --- title, so the two tabs are distinguishable side by side
out = out.replace(/<title>([^<]*)<\/title>/, '<title>$1 · KinaPT colours</title>');

// --- a small marker so it is obvious which build is on screen
out = out.replace('<div class="logo">KINA<b>·</b>OS',
                  '<div class="logo" data-build="brand">KINA<b>·</b>OS');

fs.writeFileSync(path.join(ROOT, 'brand.html'), out);
console.log(`brand.html written (${out.length} bytes)`);
